import json
import re

with open('exact_sentences_map.json', 'r', encoding='utf-8') as f:
    sentences = json.load(f)

# List of (pattern, meaning) pairs. Order matters (longest/most specific first).
replacements = [
    (r'<ruby>絶対<rt>ぜったい</rt></ruby>に<ruby>行<rt>い</rt></ruby>', 'Definitely go'),
    (r'3<ruby>年<rt>ねん</rt></ruby><ruby>前<rt>まえ</rt></ruby>', '3 years ago'),
    (r'<ruby>行<rt>い</rt></ruby>く<ruby>前<rt>まえ</rt></ruby>は', 'before going'),
    (r'<ruby>食<rt>た</rt></ruby>べ<ruby>物<rt>もの</rt></ruby>', 'food'),
    (r'<ruby>行<rt>い</rt></ruby>く<ruby>前<rt>まえ</rt></ruby>', 'before going'),
    (r'<ruby>引<rt>ひ</rt></ruby>っ<ruby>越<rt>こ</rt></ruby>す', 'To move'),
    (r'<ruby>提出<rt>ていしゅつ</rt></ruby>していただけますか', 'Could you submit'),
    (r'<ruby>連絡<rt>れんらく</rt></ruby>できませんでした', 'could not contact'),
    (r'<ruby>練習<rt>れんしゅう</rt></ruby>させられました', 'Was made to practice'),
    (r'<ruby>勉強します<rt>べんきょうします</rt></ruby>', 'to study'),
    (r'<ruby>手伝<rt>てつだ</rt></ruby>ってもらえますか', 'Can you help me'),
    (r'お<ruby>世話<rt>せわ</rt></ruby>になっております', 'Indebted / Thank you for your support'),
    (r'<ruby>公共交通<rt>こうきょうこうつう</rt></ruby>', 'public transportation'),
    (r'<ruby>食<rt>た</rt></ruby>べたことがありません', 'Have not eaten'),
    (r'<ruby>美味<rt>おい</rt></ruby>しくなかったです', 'was not delicious'),
    (r'<ruby>大変<rt>たいへん</rt></ruby>じゃなかった', 'was not tough'),
    (r'<ruby>勉強<rt>べんきょう</rt></ruby>しています', 'is studying'),
    (r'<ruby>怠<rt>なま</rt></ruby>けるようになります', 'starts to slack off / becomes lazy'),
    (r'<ruby>行<rt>い</rt></ruby>ったほうがいいですよ', 'you should go'),
    (r'<ruby>手伝<rt>てつだ</rt></ruby>ってほしいです', 'Want you to help'),
    (r'<ruby>予約<rt>よやく</rt></ruby>しておきました', 'Made a reservation in advance'),
    (r'<ruby>残業<rt>ざんぎょう</rt></ruby>させられた', 'was forced to work overtime'),
    (r'<ruby>考<rt>かんが</rt></ruby>えさせてください', 'Please let me think'),
    (r'<ruby>提出<rt>ていしゅつ</rt></ruby>いたします', 'Will submit (humble)'),
    (r'<ruby>文化交流<rt>ぶんかこうりゅう</rt></ruby>', 'cultural exchange'),
    (r'<ruby>練習<rt>れんしゅう</rt></ruby>させられま', 'was forced to practice'),
    (r'<ruby>出<rt>だ</rt></ruby>さなければならない', 'Must submit / Must turn in'),
    (r'<ruby>食<rt>た</rt></ruby>べたことがあります', 'Have eaten'),
    (r'<ruby>行<rt>い</rt></ruby>ったことがあります', 'Have been to'),
    (r'<ruby>勉強<rt>べんきょう</rt></ruby>しました', 'studied'),
    (r'<ruby>盛<rt>さか</rt></ruby>んになるでしょう', 'will probably thrive / become active'),
    (r'<ruby>上手<rt>じょうず</rt></ruby>になります', 'Become good at'),
    (r'<ruby>移動<rt>いどう</rt></ruby>するそうです', 'I heard will move'),
    (r'<ruby>結婚<rt>けっこん</rt></ruby>するらしい', 'Seems will marry'),
    (r'<ruby>言<rt>い</rt></ruby>われてしまいました', 'Was told regretfully'),
    (r'<ruby>壊<rt>こわ</rt></ruby>れてしまいまして', 'Broke regretfully'),
    (r'<ruby>遅<rt>おく</rt></ruby>れてしまいました', 'Was late regretfully'),
    (r'<ruby>勉強<rt>べんきょう</rt></ruby>します', 'to study'),
    (r'<ruby>飲みません<rt>のみません</rt></ruby>', 'do not drink'),
    (r'<ruby>見<rt>み</rt></ruby>たことがあります', 'Have seen'),
    (r'<ruby>小学校<rt>しょうがっこう</rt></ruby>', 'elementary school'),
    (r'<ruby>美味<rt>おい</rt></ruby>しかったです', 'was delicious'),
    (r'<ruby>親切<rt>しんせつ</rt></ruby>じゃない', 'is not kind'),
    (r'<ruby>勉強<rt>べんきょう</rt></ruby>したい', 'want to study'),
    (r'<ruby>治<rt>なお</rt></ruby>ってほしいです', 'Want it to heal / recover'),
    (r'<ruby>勉強<rt>べんきょう</rt></ruby>すれば', 'if you study'),
    (r'<ruby>話<rt>はな</rt></ruby>せませんでした', 'could not speak'),
    (r'<ruby>食<rt>た</rt></ruby>べてしまいました', 'Ate completely'),
    (r'<ruby>発達<rt>はったつ</rt></ruby>している', 'is developed'),
    (r'<ruby>取<rt>と</rt></ruby>りかからせられて', 'Was forced to start'),
    (r'<ruby>親切<rt>しんせつ</rt></ruby>でした', 'was kind'),
    (r'<ruby>好<rt>す</rt></ruby>きじゃなかった', 'did not like'),
    (r'<ruby>大変<rt>たいへん</rt></ruby>でした', 'was tough'),
    (r'<ruby>便利<rt>べんり</rt></ruby>になれば', 'if it becomes convenient'),
    (r'<ruby>話<rt>はな</rt></ruby>してください', 'Please speak'),
    (r'<ruby>旅行<rt>りょこう</rt></ruby>したい', 'Want to travel'),
    (r'<ruby>行<rt>い</rt></ruby>ったほうがいい', 'Should go'),
    (r'<ruby>遅刻<rt>ちこく</rt></ruby>しました', 'Was late'),
    (r'<ruby>発達<rt>はったつ</rt></ruby>すれば', 'if it develops'),
    (r'<ruby>世界中<rt>せかいじゅう</rt></ruby>', 'worldwide / all over the world'),
    (r'<ruby>食べます<rt>たべます</rt></ruby>', 'to eat'),
    (r'<ruby>決<rt>き</rt></ruby>めていません', 'Have not decided'),
    (r'お<ruby>願<rt>ねが</rt></ruby>いします', 'please'),
    (r'<ruby>言<rt>い</rt></ruby>っていました', 'Was saying'),
    (r'<ruby>寒<rt>さむ</rt></ruby>くなかった', 'was not cold'),
    (r'<ruby>勉強<rt>べんきょう</rt></ruby>し', 'study'),
    (r'<ruby>夏休み<rt>なつやすみ</rt></ruby>', 'summer vacation'),
    (r'<ruby>図書館<rt>としょかん</rt></ruby>', 'library'),
    (r'<ruby>自転車<rt>じてんしゃ</rt></ruby>', 'bicycle'),
    (r'<ruby>美味<rt>おい</rt></ruby>しくない', 'is not delicious'),
    (r'<ruby>暖<rt>あたた</rt></ruby>かかった', 'was warm'),
    (r'<ruby>忙<rt>いそが</rt></ruby>しかった', 'was busy'),
    (r'<ruby>難<rt>むずか</rt></ruby>しいです', 'is difficult'),
    (r'<ruby>行<rt>い</rt></ruby>ってみたいと', 'Want to try going'),
    (r'<ruby>行<rt>い</rt></ruby>くつもりです', 'Intend to go'),
    (r'<ruby>降<rt>ふ</rt></ruby>っているから', 'Because it is raining'),
    (r'<ruby>言<rt>い</rt></ruby>っていたので', 'Because they said'),
    (r'<ruby>来<rt>き</rt></ruby>てくださって', 'Thank you for coming'),
    (r'<ruby>開<rt>あ</rt></ruby>けてあります', 'Is left open'),
    (r'<ruby>連絡<rt>れんらく</rt></ruby>した', 'Contacted'),
    (r'<ruby>食<rt>た</rt></ruby>べられました', 'Was eaten'),
    (r'<ruby>考<rt>かんが</rt></ruby>えさせて', 'Let me think'),
    (r'<ruby>話<rt>はな</rt></ruby>せるならば', 'if you can speak'),
    (r'<ruby>提出<rt>ていしゅつ</rt></ruby>し', 'submit'),
    (r'<ruby>始<rt>はじ</rt></ruby>めました', 'Started'),
    (r'<ruby>手伝<rt>てつだ</rt></ruby>って', 'to help'),
    (r'<ruby>住<rt>す</rt></ruby>んでいます', 'Living'),
    (r'<ruby>二度<rt>にど</rt></ruby>くらい', 'about twice'),
    (r'<ruby>行<rt>い</rt></ruby>ってみたい', 'want to try going'),
    (r'<ruby>田中<rt>たなか</rt></ruby>さん', 'Mr./Ms. Tanaka'),
    (r'アメリカ<ruby>人<rt>じん</rt></ruby>', 'American person'),
    (r'<ruby>東京<rt>とうきょう</rt></ruby>', 'Tokyo'),
    (r'<ruby>日本語<rt>にほんご</rt></ruby>', 'Japanese language'),
    (r'<ruby>病院<rt>びょういん</rt></ruby>', 'hospital'),
    (r'お<ruby>会計<rt>かいけい</rt></ruby>', 'check / bill'),
    (r'<ruby>宿題<rt>しゅくだい</rt></ruby>', 'homework'),
    (r'<ruby>選<rt>えら</rt></ruby>びました', 'Chose'),
    (r'<ruby>面白<rt>おもしろ</rt></ruby>い', 'interesting / funny'),
    (r'<ruby>週末<rt>しゅうまつ</rt></ruby>', 'weekend'),
    (r'<ruby>一緒<rt>いっしょ</rt></ruby>に', 'together'),
    (r'<ruby>少し<rt>すこし</rt></ruby>しか', 'only a little'),
    (r'<ruby>絶対<rt>ぜったい</rt></ruby>に', 'definitely / absolutely'),
    (r'<ruby>子<rt>こ</rt></ruby>どものころ', 'childhood / when (I) was a child'),
    (r'<ruby>考<rt>かんが</rt></ruby>えます', 'think / consider'),
    (r'<ruby>見<rt>み</rt></ruby>ることです', 'To watch'),
    (r'<ruby>食<rt>た</rt></ruby>べませんか', 'Won\'t you eat?'),
    (r'<ruby>作<rt>つく</rt></ruby>ることが', 'Making (cooking)'),
    (r'<ruby>頭<rt>あたま</rt></ruby>がいい', 'Smart'),
    (r'<ruby>食<rt>た</rt></ruby>べられます', 'Can eat'),
    (r'<ruby>遅<rt>おく</rt></ruby>れました', 'Was late'),
    (r'<ruby>欠<rt>か</rt></ruby>かしません', 'Do not miss'),
    (r'<ruby>壊<rt>こわ</rt></ruby>れました', 'Broke (intransitive)'),
    (r'<ruby>壊<rt>こわ</rt></ruby>しました', 'Broke (transitive)'),
    (r'<ruby>開<rt>あ</rt></ruby>いています', 'Is open'),
    (r'<ruby>降<rt>ふ</rt></ruby>りそうです', 'Looks like it will rain'),
    (r'<ruby>考<rt>かん</rt></ruby>がえます', 'Think'),
    (r'<ruby>影響<rt>えいきょう</rt></ruby>', 'influence / impact'),
    (r'<ruby>来週<rt>らいしゅう</rt></ruby>', 'next week'),
    (r'<ruby>考<rt>かんが</rt></ruby>えさせ', 'let me think'),
    (r'<ruby>練習<rt>れんしゅう</rt></ruby>', 'practice'),
    (r'<ruby>発達<rt>はったつ</rt></ruby>し', 'develop'),
    (r'<ruby>食<rt>た</rt></ruby>べました', 'Ate'),
    (r'<ruby>食<rt>た</rt></ruby>べないで', 'Without eating'),
    (r'<ruby>見ます<rt>みます</rt></ruby>', 'to watch / see'),
    (r'<ruby>行<rt>い</rt></ruby>きました', 'Went'),
    (r'<ruby>飲<rt>の</rt></ruby>みません', 'Do not drink'),
    (r'<ruby>降<rt>ふ</rt></ruby>っている', 'is falling'),
    (r'<ruby>休<rt>やす</rt></ruby>みます', 'Rest / Take a day off'),
    (r'<ruby>出<rt>で</rt></ruby>かけます', 'Go out'),
    (r'<ruby>思<rt>おも</rt></ruby>います', 'Think'),
    (r'<ruby>食<rt>た</rt></ruby>べません', 'Do not eat'),
    (r'<ruby>行<rt>い</rt></ruby>かなきゃ', 'Must go'),
    (r'<ruby>言<rt>い</rt></ruby>っていた', 'was saying'),
    (r'<ruby>彼女<rt>かのじょ</rt></ruby>', 'she / her'),
    (r'<ruby>友達<rt>ともだち</rt></ruby>', 'friend'),
    (r'<ruby>先生<rt>せんせい</rt></ruby>', 'teacher'),
    (r'<ruby>学生<rt>がくせい</rt></ruby>', 'student'),
    (r'<ruby>京都<rt>きょうと</rt></ruby>', 'Kyoto'),
    (r'<ruby>人口<rt>じんこう</rt></ruby>', 'population'),
    (r'<ruby>三人<rt>さんにん</rt></ruby>', 'three (people)'),
    (r'<ruby>建物<rt>たてもの</rt></ruby>', 'building'),
    (r'<ruby>昼<rt>ひる</rt></ruby>ごはん', 'lunch'),
    (r'<ruby>朝<rt>あさ</rt></ruby>ごはん', 'breakfast'),
    (r'<ruby>会社<rt>かいしゃ</rt></ruby>', 'company'),
    (r'<ruby>学校<rt>がっこう</rt></ruby>', 'school'),
    (r'<ruby>納豆<rt>なっとう</rt></ruby>', 'natto (fermented soybeans)'),
    (r'<ruby>料理<rt>りょうり</rt></ruby>', 'cooking'),
    (r'<ruby>交番<rt>こうばん</rt></ruby>', 'police box'),
    (r'<ruby>病気<rt>びょうき</rt></ruby>', 'illness'),
    (r'<ruby>美味<rt>おい</rt></ruby>しい', 'delicious'),
    (r'<ruby>難<rt>むずか</rt></ruby>しい', 'difficult'),
    (r'<ruby>寒<rt>さむ</rt></ruby>かった', 'was cold'),
    (r'<ruby>親切<rt>しんせつ</rt></ruby>', 'kind'),
    (r'<ruby>大好<rt>だいす</rt></ruby>き', 'love / really like'),
    (r'<ruby>大変<rt>たいへん</rt></ruby>', 'tough / hard'),
    (r'<ruby>毎日<rt>まいにち</rt></ruby>', 'every day'),
    (r'<ruby>毎朝<rt>まいあさ</rt></ruby>', 'every morning'),
    (r'<ruby>最近<rt>さいきん</rt></ruby>', 'recently'),
    (r'<ruby>全然<rt>ぜんぜん</rt></ruby>', 'not at all'),
    (r'もう<ruby>少<rt>すこ</rt></ruby>し', 'a little more'),
    (r'<ruby>足<rt>た</rt></ruby>りません', 'Is not enough'),
    (r'<ruby>減<rt>へ</rt></ruby>っていく', 'decrease / diminish'),
    (r'<ruby>比<rt>くら</rt></ruby>べると', 'compared to'),
    (r'<ruby>人間<rt>にんげん</rt></ruby>', 'human / people'),
    (r'<ruby>若者<rt>わかもの</rt></ruby>', 'young people / youth'),
    (r'<ruby>予約<rt>よやく</rt></ruby>し', 'reserve'),
    (r'<ruby>連絡<rt>れんらく</rt></ruby>', 'contact / communication'),
    (r'<ruby>計画<rt>けいかく</rt></ruby>', 'plan'),
    (r'<ruby>旅行<rt>りょこう</rt></ruby>', 'travel / trip'),
    (r'<ruby>上司<rt>じょうし</rt></ruby>', 'boss'),
    (r'<ruby>上手<rt>じょうず</rt></ruby>', 'skillful / good at'),
    (r'わざわざ<ruby>来<rt>き</rt></ruby>', 'come all the way'),
    (r'<ruby>電車<rt>でんしゃ</rt></ruby>', 'train'),
    (r'<ruby>食<rt>た</rt></ruby>べます', 'Eat'),
    (r'<ruby>見<rt>み</rt></ruby>ました', 'Watched / Saw'),
    (r'<ruby>行<rt>い</rt></ruby>きます', 'Go'),
    (r'<ruby>来<rt>き</rt></ruby>ました', 'came'),
    (r'<ruby>寝<rt>ね</rt></ruby>ないで', 'Without sleeping'),
    (r'<ruby>治<rt>なお</rt></ruby>って', 'to get better'),
    (r'<ruby>弾<rt>ひ</rt></ruby>きます', 'Play (instrument)'),
    (r'<ruby>話<rt>はな</rt></ruby>して', 'to speak'),
    (r'<ruby>医者<rt>いしゃ</rt></ruby>', 'doctor'),
    (r'<ruby>日本<rt>にほん</rt></ruby>', 'Japan'),
    (r'<ruby>火<rt>ひ</rt></ruby>まつり', 'fire festival'),
    (r'<ruby>三個<rt>さんこ</rt></ruby>', 'three (objects)'),
    (r'<ruby>仕事<rt>しごと</rt></ruby>', 'work / job'),
    (r'<ruby>名前<rt>なまえ</rt></ruby>', 'name'),
    (r'<ruby>映画<rt>えいが</rt></ruby>', 'movie'),
    (r'<ruby>試験<rt>しけん</rt></ruby>', 'exam'),
    (r'<ruby>趣味<rt>しゅみ</rt></ruby>', 'hobby'),
    (r'<ruby>刺身<rt>さしみ</rt></ruby>', 'sashimi (raw fish)'),
    (r'<ruby>財布<rt>さいふ</rt></ruby>', 'wallet'),
    (r'<ruby>予定<rt>よてい</rt></ruby>', 'plan / schedule'),
    (r'<ruby>時間<rt>じかん</rt></ruby>', 'time'),
    (r'<ruby>一度<rt>いちど</rt></ruby>', 'once'),
    (r'<ruby>何度<rt>なんど</rt></ruby>', 'how many times'),
    (r'<ruby>綺麗<rt>きれい</rt></ruby>', 'beautiful / clean'),
    (r'<ruby>楽<rt>たの</rt></ruby>しい', 'Fun'),
    (r'<ruby>今日<rt>きょう</rt></ruby>', 'today'),
    (r'<ruby>明日<rt>あした</rt></ruby>', 'tomorrow'),
    (r'<ruby>昨日<rt>きのう</rt></ruby>', 'yesterday'),
    (r'<ruby>何時<rt>なんじ</rt></ruby>', 'what time'),
    (r'<ruby>怠<rt>なま</rt></ruby>ける', 'To slack off'),
    (r'<ruby>弾<rt>ひ</rt></ruby>けます', 'can play'),
    (r'<ruby>回<rt>まわ</rt></ruby>ると', 'If you turn'),
    (r'<ruby>行<rt>い</rt></ruby>くなら', 'If you go'),
    (r'<ruby>与<rt>あた</rt></ruby>える', 'give / provide'),
    (r'<ruby>運<rt>はこ</rt></ruby>んで', 'To carry (te-form)'),
    (r'<ruby>話<rt>はな</rt></ruby>せる', 'can speak'),
    (r'<ruby>予約<rt>よやく</rt></ruby>', 'reservation'),
    (r'お<ruby>世話<rt>せわ</rt></ruby>', 'care / support'),
    (r'<ruby>会議<rt>かいぎ</rt></ruby>', 'meeting'),
    (r'<ruby>遅刻<rt>ちこく</rt></ruby>', 'tardiness / being late'),
    (r'<ruby>食<rt>た</rt></ruby>べられ', 'can eat'),
    (r'<ruby>遅<rt>おく</rt></ruby>れま', 'be late'),
    (r'<ruby>機械<rt>きかい</rt></ruby>', 'machine'),
    (r'<ruby>食<rt>た</rt></ruby>べた', 'ate (casual)'),
    (r'<ruby>見<rt>み</rt></ruby>ます', 'Watch / See'),
    (r'<ruby>行<rt>い</rt></ruby>った', 'went (casual)'),
    (r'<ruby>行<rt>い</rt></ruby>って', 'to go (te-form)'),
    (r'<ruby>浴<rt>あび</rt></ruby>て', 'Bathe (te-form)'),
    (r'<ruby>寝<rt>ね</rt></ruby>ます', 'Sleep'),
    (r'<ruby>作<rt>つく</rt></ruby>る', 'to make'),
    (r'<ruby>少<rt>すこ</rt></ruby>し', 'a little'),
    (r'<ruby>私<rt>わたし</rt></ruby>', 'I / me'),
    (r'<ruby>車<rt>くるま</rt></ruby>', 'car'),
    (r'お<ruby>酒<rt>さけ</rt></ruby>', 'alcohol'),
    (r'<ruby>部屋<rt>へや</rt></ruby>', 'room'),
    (r'<ruby>風邪<rt>かぜ</rt></ruby>', 'cold (illness)'),
    (r'<ruby>寿司<rt>すし</rt></ruby>', 'sushi'),
    (r'<ruby>早<rt>はや</rt></ruby>く', 'early / fast'),
    (r'<ruby>週<rt>しゅう</rt></ruby>', 'week'),
    (r'<ruby>特<rt>とく</rt></ruby>に', 'especially'),
    (r'<ruby>実<rt>じつ</rt></ruby>は', 'actually / in fact'),
    (r'お<ruby>金<rt>かね</rt></ruby>', 'money'),
    (r'<ruby>前<rt>まえ</rt></ruby>に', 'before'),
    (r'<ruby>悪<rt>わる</rt></ruby>い', 'bad / negative'),
    (r'<ruby>降<rt>ふ</rt></ruby>ると', 'Fall (rain, snow)'),
    (r'<ruby>話<rt>はな</rt></ruby>す', 'speak'),
    (r'<ruby>書<rt>か</rt></ruby>けば', 'If you write'),
    (r'<ruby>近<rt>ちか</rt></ruby>い', 'near / close'),
    (r'<ruby>安<rt>やす</rt></ruby>い', 'cheap'),
    (r'<ruby>話<rt>はな</rt></ruby>せ', 'speak'),
    (r'<ruby>遅<rt>おく</rt></ruby>れ', 'be late'),
    (r'<ruby>あけ<rt>あけ</rt></ruby>', 'open'),
    (r'<ruby>言<rt>い</rt></ruby>われ', 'be told'),
    (r'<ruby>壊<rt>こわ</rt></ruby>れ', 'break'),
    (r'<ruby>見<rt>み</rt></ruby>る', 'to watch / see (dictionary form)'),
    (r'<ruby>見<rt>み</rt></ruby>た', 'watched / saw (casual)'),
    (r'<ruby>行<rt>い</rt></ruby>く', 'to go (dictionary form)'),
    (r'<ruby>降<rt>ふ</rt></ruby>る', 'to fall (rain/snow)'),
    (r'<ruby>見<rt>み</rt></ruby>に', 'to see (purpose)'),
    (r'<ruby>飲<rt>の</rt></ruby>み', 'drink'),
    (r'<ruby>食<rt>た</rt></ruby>べ', 'eat'),
    (r'<ruby>山<rt>やま</rt></ruby>', 'mountain'),
    (r'<ruby>水<rt>みず</rt></ruby>', 'water'),
    (r'<ruby>本<rt>ほん</rt></ruby>', 'book'),
    (r'<ruby>駅<rt>えき</rt></ruby>', 'station'),
    (r'<ruby>猫<rt>ねこ</rt></ruby>', 'cat'),
    (r'<ruby>雨<rt>あめ</rt></ruby>', 'rain'),
    (r'<ruby>肉<rt>にく</rt></ruby>', 'meat'),
    (r'<ruby>家<rt>いえ</rt></ruby>', 'house / home'),
    (r'<ruby>好<rt>す</rt></ruby>き', 'like'),
    (r'<ruby>今<rt>いま</rt></ruby>', 'now'),
    (r'<ruby>何<rt>なん</rt></ruby>', 'what'),
    (r'<ruby>国<rt>くに</rt></ruby>', 'country'),
    (r'<ruby>弾<rt>ひ</rt></ruby>け', 'can play'),
    (r'<ruby>足<rt>た</rt></ruby>り', 'be sufficient'),
    (r'<ruby>窓<rt>まど</rt></ruby>', 'window'),
    (r'<ruby>見<rt>み</rt></ruby>', 'see'),
    (r'<ruby>欠<rt>か</rt></ruby>', 'lack / miss'),
    (r'おうかがいしてもよろしいでしょうか', 'May I ask (humble)'),
    (r'ではありませんでした', 'was not'),
    (r'ありがとうございます', 'thank you very much'),
    (r'(?<!は)はい、', 'yes,'),
    (r'ナッツアレルギー', 'nut allergy'),
    (r'おもちいたします', 'Will carry (humble)'),
    (r'とっておきました', 'Kept in advance'),
    (r'みつかりました', 'Was found'),
    (r'ことができます', 'can / be able to'),
    (r'うまくなります', 'Will become good'),
    (r'いただきました', 'Received (humble)'),
    (r'つながらなくて', 'Couldn\'t connect'),
    (r'結婚するらしい', 'seems will marry'),
    (r'開けてあります', 'is left open'),
    (r'ニューヨーク', 'New York'),
    (r'してあります', 'has been done (transitive state)'),
    (r'おいしくない', 'Not delicious'),
    (r'もらいました', 'Received'),
    (r'ひいたみたい', 'Looks like caught (a cold)'),
    (r'テクノロジー', 'technology'),
    (r'バックアップ', 'backup'),
    (r'移動するそう', 'I heard will move'),
    (r'開いています', 'is open'),
    (r'ありません', 'there is not / do not have'),
    (r'あげました', 'gave'),
    (r'プレゼント', 'present / gift'),
    (r'勉強します', 'to study'),
    (r'ありました', 'Was / Existed'),
    (r'あけてある', 'Is left open'),
    (r'くれました', 'Gave to me'),
    (r'しまいまし', 'regretfully did'),
    (r'アドバイス', 'advice'),
    (r'壊れました', 'broke (intransitive)'),
    (r'壊しました', 'broke (transitive)'),
    (r'あります', 'there is / have (inanimate)'),
    (r'いました', 'was / were (animate)'),
    (r'ください', 'please'),
    (r'しました', 'did'),
    (r'らーめん', 'ramen'),
    (r'シャワー', 'shower'),
    (r'ゆっくり', 'slowly'),
    (r'おすすめ', 'recommendation'),
    (r'いちばん', 'most / number one'),
    (r'なるほど', 'the more ...'),
    (r'するほど', 'the more ...'),
    (r'手伝って', 'To help (te-form)'),
    (r'レポート', 'report'),
    (r'いただけ', 'receive (humble)'),
    (r'アパート', 'apartment'),
    (r'わざわざ', 'intentionally / taking the trouble'),
    (r'おもちゃ', 'toy'),
    (r'降りそう', 'looks like it will fall'),
    (r'引っ越す', 'move house'),
    (r'でした', 'was'),
    (r'います', 'there is / have (animate)'),
    (r'ほしい', 'want'),
    (r'ひいた', 'caught (a cold)'),
    (r'あまり', 'not very'),
    (r'つもり', 'plan / intention'),
    (r'わたし', 'I / me'),
    (r'りんご', 'apple'),
    (r'ごはん', 'meal / rice'),
    (r'ギター', 'guitar'),
    (r'きれい', 'beautiful / clean'),
    (r'おおい', 'many'),
    (r'いくら', 'how much'),
    (r'いいえ', 'no'),
    (r'はい、', 'yes,'),
    (r'とても', 'very'),
    (r'だから', 'so / therefore'),
    (r'なので', 'because of that'),
    (r'もっと', 'more'),
    (r'あれば', 'if there is / have'),
    (r'それで', 'therefore / and then / so'),
    (r'いいと', 'good'),
    (r'けれど', 'but / however'),
    (r'さらに', 'furthermore / in addition'),
    (r'いつも', 'always'),
    (r'までに', 'by (deadline)'),
    (r'ほうが', 'is better / more'),
    (r'SNS', 'SNS / social media'),
    (r'おきま', 'in advance'),
    (r'ひどい', 'terrible / awful'),
    (r'ホテル', 'hotel'),
    (r'られま', 'can be done (passive/potential)'),
    (r'ケーキ', 'cake'),
    (r'ピアノ', 'piano'),
    (r'日本語', 'Japanese language'),
    (r'行く前', 'before going'),
    (r'郵便局', 'post office'),
    (r'クラス', 'class'),
    (r'なかで', 'among / in'),
    (r'こと', 'thing (nominalizer)'),
    (r'なん', 'what'),
    (r'した', 'did'),
    (r'サラ', 'Sarah'),
    (r'ペン', 'pen'),
    (r'ヨガ', 'yoga'),
    (r'あれ', 'that over there'),
    (r'あの', 'that (modifier)'),
    (r'これ', 'this'),
    (r'この', 'this (modifier)'),
    (r'その', 'that (modifier)'),
    (r'でも', 'but'),
    (r'まだ', 'not yet'),
    (r'よく', 'often'),
    (r'もう', 'already'),
    (r'ため', 'due to / because of'),
    (r'もし', 'if'),
    (r'より', 'more (comparative)'),
    (r'全部', 'all / completely'),
    (r'予算', 'budget'),
    (r'あけ', 'open'),
    (r'いる', 'exist / be'),
    (r'いい', 'good'),
    (r'話す', 'speak'),
    (r'話せ', 'can speak'),
    (r'日本', 'Japan'),
    (r'弾け', 'can play'),
    (r'食べ', 'eat'),
    (r'電車', 'train'),
    (r'携帯', 'cellphone'),
    (r'来年', 'next year'),
    (r'結婚', 'marriage'),
    (r'先生', 'teacher'),
    (r'会社', 'company'),
    (r'移動', 'move'),
    (r'降り', 'fall / rain'),
    (r'風邪', 'cold (illness)'),
    (r'今度', 'this time / next time'),
    (r'日記', 'diary'),
    (r'雨', 'rain'),
    (r'窓', 'window'),
    (r'私', 'I / me'),
    (r'右', 'right'),
]

# Sort by length descending to match longest phrases first
replacements.sort(key=lambda x: len(x[0]), reverse=True)

def annotate(jp_str):
    res = jp_str
    
    mapping = {}
    counter = 0
    
    for r in replacements:
        pattern, meaning = r
        try:
            match = re.search(pattern, res)
            if match:
                token = f"@@TOKEN_{counter}@@"
                mapping[token] = f'<span class="tooltip-word" data-tooltip="{meaning}" onclick="saveWordClick(this)">{match.group(0)}</span>'
                res = res.replace(match.group(0), token)
                counter += 1
        except Exception as e:
            if pattern in res:
                token = f"@@TOKEN_{counter}@@"
                mapping[token] = f'<span class="tooltip-word" data-tooltip="{meaning}" onclick="saveWordClick(this)">{pattern}</span>'
                res = res.replace(pattern, token)
                counter += 1

    for token, html in mapping.items():
        res = res.replace(token, html)
        
    return res

annotated_map = {}
for jp in sentences.keys():
    annotated_map[jp] = annotate(jp)

with open('annotated_sentences.json', 'w', encoding='utf-8') as f:
    json.dump(annotated_map, f, ensure_ascii=False, indent=2)

print("Generated annotated_sentences.json with comprehensive mapping.")
